# docker-compose file
version: '3'

services:
  mypsql:
    image: mypsql:latest
    environment:
      POSTGRES_PASSWORD: mypassword
      #POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - project-network
    volumes:
      - myserver-database:/var/lib/postgresql/data
      
  myredis:
    image: redis
    networks:
      - project-network

  myserver:
    image: myserver:latest
    networks:
      - project-network

  mynginx:
    image: mynginx:latest
    ports:
     - "9000:80"
    networks:
      - project-network

  myworker:
    image: myworker:latest
    networks:
      - project-network


networks:
  project-network:
volumes:
  myserver-database:
