FROM ubuntu:latest

ENV DEBUG="True"
ENV CELERY_BROKER_URL="redis://myredis:6379/0"
ENV CELERY_RESULT_BACKEND="redis://myredis:6379/0"
ENV DJANGO_DB="postgresql"
ENV POSTGRES_HOST="mypsql"
ENV POSTGRES_NAME="mydb"
ENV POSTGRES_USER="myuser"
ENV POSTGRES_PASSWORD="mypassword"
ENV POSTGRES_PORT="5432"

# Set the working directory
WORKDIR /home

# Copy the application code
COPY ./ /home/

# Install Python 3.8
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC
RUN apt-get update && \
    apt-get install -y tzdata && \
    apt-get install -y software-properties-common && \
    add-apt-repository -y ppa:deadsnakes/ppa && \
    apt-get update && \
    apt-get install -y python3.8 python3.8-distutils && \
    apt-get install -y wget && \
    wget https://bootstrap.pypa.io/get-pip.py && \
    python3.8 get-pip.py && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install Gunicorn
RUN pip install gunicorn
RUN pip install -r requirements.txt 

RUN chmod +x /home/backend/worker-entrypoint.sh


CMD ["./backend/worker-entrypoint.sh"]
